/*******************************************************************************
*
* Header file generated by RDP on Oct 22 2013 00:53:56 from regex.bnf
*
*******************************************************************************/
#ifndef REGEX_H
#define REGEX_H

#include "arg.h"
#include "graph.h"
#include "hist.h"
#include "memalloc.h"
#include "scan.h"
#include "set.h"
#include "symbol.h"
#include "textio.h"


/* Maximum number of passes */
#define RDP_PASSES 1

/* Time and date stamp */
#define RDP_STAMP "Generated on Oct 22 2013 00:53:56 and compiled on " __DATE__ " at " __TIME__ 

/* Token enumeration */
enum
{
RDP_TT_BOTTOM = SCAN_P_TOP,
RDP_T_35 /* # */ = SCAN_P_TOP,RDP_T_40 /* ( */,RDP_T_41 /* ) */,RDP_T_42 /* * */,RDP_T_124 /* | */,
RDP_TT_TOP
};

/* Tree data types */

typedef struct rdp_tree_node_data_struct
{
  SCAN_DATA
  
} rdp_tree_node_data;
typedef struct rdp_tree_edge_data_struct
{
  int rdp_edge_kind;
  
} rdp_tree_edge_data;

/* Symbol table support */
/* Parser start production */
void reg(void);



#endif

/* End of regex.h */
