/*******************************************************************************
*
* Parser generated by RDP on Oct 22 2013 00:53:56 from regex.bnf
*
*******************************************************************************/
#include <time.h>
#include "regex.h"

char
  *rdp_sourcefilename,          /* current source file name */
  **rdp_sourcefilenames,        /* array of source file names */
  *rdp_outputfilename = "regex.out";         /* output file name */

int
  rdp_symbol_echo = 0,                 /* symbol echo flag */
  rdp_verbose = 0,                     /* verbosity flag */
  rdp_sourcefilenumber,                /* Source file counter */
  rdp_pass;                            /* pass number */

int rdp_error_return = 0;              /* return value for main routine */

char *rdp_tokens = "IGNORE\0" 
"ID\0" "INTEGER\0" "REAL\0" "CHAR\0" "CHAR_ESC\0" "STRING\0" "STRING_ESC\0" "COMMENT\0" 
"COMMENT_VISIBLE\0" "COMMENT_NEST\0" "COMMENT_NEST_VISIBLE\0" "COMMENT_LINE\0" "COMMENT_LINE_VISIBLE\0" "EOF\0" "EOLN\0" "'#'\0" 
"'('\0" "')'\0" "'*'\0" "'|'\0" ;


/* Load keywords */
static void rdp_load_keywords(void)
{
  scan_load_keyword("#", NULL, RDP_T_35 /* # */, SCAN_P_IGNORE);
  scan_load_keyword("(", NULL, RDP_T_40 /* ( */, SCAN_P_IGNORE);
  scan_load_keyword(")", NULL, RDP_T_41 /* ) */, SCAN_P_IGNORE);
  scan_load_keyword("*", NULL, RDP_T_42 /* * */, SCAN_P_IGNORE);
  scan_load_keyword("|", NULL, RDP_T_124 /* | */, SCAN_P_IGNORE);
}

/* Set declarations */

  set_ rdp_reg_0_first = SET_NULL;
  set_ rdp_reg_12_first = SET_NULL;
  set_ rdp_reg_13_first = SET_NULL;
  set_ rdp_reg_2_first = SET_NULL;
  set_ rdp_reg_6_first = SET_NULL;
  set_ rdp_reg_7_first = SET_NULL;
  set_ rdp_reg_8_first = SET_NULL;
  set_ reg_first = SET_NULL;
  set_ reg_stop = SET_NULL;
  set_ sym_first = SET_NULL;
  set_ sym_stop = SET_NULL;

/* Initialise sets */

static void rdp_set_initialise(void)
{
  set_assign_list(&rdp_reg_0_first, SCAN_P_ID, RDP_T_35 /* # */, SET_END);
  set_assign_list(&rdp_reg_12_first, SCAN_P_ID, RDP_T_35 /* # */, RDP_T_40 /* ( */, RDP_T_42 /* * */, RDP_T_124 /* | */, SET_END);
  set_assign_list(&rdp_reg_13_first, SCAN_P_ID, RDP_T_35 /* # */, RDP_T_40 /* ( */, SET_END);
  set_assign_list(&rdp_reg_2_first, SCAN_P_ID, RDP_T_35 /* # */, RDP_T_40 /* ( */, SET_END);
  set_assign_list(&rdp_reg_6_first, SCAN_P_ID, RDP_T_35 /* # */, RDP_T_40 /* ( */, SET_END);
  set_assign_list(&rdp_reg_7_first, SCAN_P_ID, RDP_T_35 /* # */, RDP_T_40 /* ( */, SET_END);
  set_assign_list(&rdp_reg_8_first, SCAN_P_ID, RDP_T_35 /* # */, RDP_T_40 /* ( */, SET_END);
  set_assign_list(&reg_first, SCAN_P_ID, RDP_T_35 /* # */, RDP_T_40 /* ( */, SET_END);
  set_assign_list(&reg_stop, SCAN_P_ID, SCAN_P_EOF, RDP_T_35 /* # */, RDP_T_40 /* ( */, RDP_T_41 /* ) */, RDP_T_124 /* | */,SET_END);
  set_assign_list(&sym_first, SCAN_P_ID, RDP_T_35 /* # */, SET_END);
  set_assign_list(&sym_stop, SCAN_P_ID, SCAN_P_EOF, RDP_T_35 /* # */, RDP_T_40 /* ( */, RDP_T_41 /* ) */, RDP_T_42 /* * */, 
RDP_T_124 /* | */,SET_END);
}

/* Parser forward declarations and macros */
void reg(void);
static void sym(void);

/* Parser functions */
void reg(void)
{
  {
    { /* Start of rdp_reg_2 */
      while (1)
      {
        scan_test_set(NULL, &rdp_reg_2_first, &reg_stop);
        {
          if (scan_test_set(NULL, &rdp_reg_0_first, NULL))
          {
            sym();
          }
          else
          if (scan_test(NULL, RDP_T_40 /* ( */, NULL))
          {
            scan_test(NULL, RDP_T_40 /* ( */, &reg_stop);
            scan_();
            reg();
            scan_test(NULL, RDP_T_41 /* ) */, &reg_stop);
            scan_();
          }
          else
            scan_test_set(NULL, &rdp_reg_2_first, &reg_stop)          ;
          }
        break;   /* hi limit is 1! */
      }
    } /* end of rdp_reg_2 */
    if (scan_test_set(NULL, &rdp_reg_12_first, NULL))
    { /* Start of rdp_reg_12 */
      while (1)
      {
        {
          if (scan_test(NULL, RDP_T_124 /* | */, NULL))
          {
            { /* Start of rdp_reg_4 */
              while (1)
              {
                scan_test(NULL, RDP_T_124 /* | */, &reg_stop);
                {
                  scan_test(NULL, RDP_T_124 /* | */, &reg_stop);
                  scan_();
                  reg();
                  }
                if (!scan_test(NULL, RDP_T_124 /* | */, NULL)) break;
              }
            } /* end of rdp_reg_4 */
          }
          else
          if (scan_test_set(NULL, &rdp_reg_8_first, NULL))
          {
            { /* Start of rdp_reg_7 */
              while (1)
              {
                scan_test_set(NULL, &rdp_reg_7_first, &reg_stop);
                {
                  reg();
                  }
                if (!scan_test_set(NULL, &rdp_reg_7_first, NULL)) break;
              }
            } /* end of rdp_reg_7 */
          }
          else
          if (scan_test(NULL, RDP_T_42 /* * */, NULL))
          {
            { /* Start of rdp_reg_10 */
              while (1)
              {
                scan_test(NULL, RDP_T_42 /* * */, &reg_stop);
                {
                  scan_test(NULL, RDP_T_42 /* * */, &reg_stop);
                  scan_();
                  }
                if (!scan_test(NULL, RDP_T_42 /* * */, NULL)) break;
              }
            } /* end of rdp_reg_10 */
          }
          else
            scan_test_set(NULL, &rdp_reg_12_first, &reg_stop)          ;
          }
        break;   /* hi limit is 1! */
      }
    } /* end of rdp_reg_12 */
    scan_test_set(NULL, &reg_stop, &reg_stop);
   }
}

static void sym(void)
{
  {
    if (scan_test(NULL, SCAN_P_ID, NULL))
    {
      scan_test(NULL, SCAN_P_ID, &sym_stop);
      scan_();
    }
    else
    if (scan_test(NULL, RDP_T_35 /* # */, NULL))
    {
      scan_test(NULL, RDP_T_35 /* # */, &sym_stop);
      scan_();
    }
    else
      scan_test_set(NULL, &sym_first, &sym_stop)    ;
    scan_test_set(NULL, &sym_stop, &sym_stop);
   }
}

int main(int argc, char *argv[])
{
  clock_t rdp_finish_time, rdp_start_time = clock();
  int
    rdp_symbol_statistics = 0,    /* show symbol_ table statistics flag */
    rdp_line_echo_all = 0,        /* make a listing on all passes flag */
    rdp_filter = 0,               /* filter flag */
    rdp_line_echo = 0,            /* make listing flag */

    rdp_lexicalise = 0;            /* print lexicalised output flag */

  unsigned long rdp_textsize = 35000l;   /* size of scanner text array */

  unsigned long rdp_tabwidth = 8l;   /* tab expansion width */

  char* rdp_vcg_filename = NULL;      /* filename for -V option */

  arg_message("rdparser\n" RDP_STAMP "\n\n""Usage: regex [options] source");

  arg_message("");
  arg_boolean('f', "Filter mode (read from stdin and write to stdout)", &rdp_filter);
  arg_boolean('l', "Make a listing", &rdp_line_echo);
  arg_boolean('L', "Print lexicalised source file", &rdp_lexicalise);
  arg_string ('o', "Write output to filename", &rdp_outputfilename);
  arg_boolean('s', "Echo each scanner symbol as it is read", &rdp_symbol_echo);
  arg_boolean('S', "Print summary symbol table statistics", &rdp_symbol_statistics);
  arg_numeric('t', "Tab expansion width (default 8)", &rdp_tabwidth);
  arg_numeric('T', "Text buffer size in bytes for scanner (default 20000)", &rdp_textsize);
  arg_boolean('v', "Set verbose mode", &rdp_verbose);
  arg_string ('V', "Write derivation tree to filename in VCG format", &rdp_vcg_filename);

  rdp_sourcefilenames = arg_process(argc, argv);

  /* Fix up filetypes */
  for (rdp_sourcefilenumber = 0; rdp_sourcefilenames[rdp_sourcefilenumber] != NULL; rdp_sourcefilenumber++)
    rdp_sourcefilenames[rdp_sourcefilenumber] = text_default_filetype(rdp_sourcefilenames[rdp_sourcefilenumber], "");

  if (rdp_filter)
  {
    rdp_sourcefilenames[0] = "-";
    rdp_outputfilename = "-";
    rdp_sourcefilenames[1] = NULL;     /* make sure no further filenames are taken from the array */

  }
  if ((rdp_sourcefilename = rdp_sourcefilenames[0]) == NULL)
     arg_help("no source files specified");

  if (rdp_sourcefilenames[1] != NULL)
    text_message(TEXT_FATAL, "multiple source files not allowed\n");
  text_init(rdp_textsize, 25, 100, (int) rdp_tabwidth);
  scan_init(0, 0, 0, rdp_symbol_echo, rdp_tokens);
  if (rdp_lexicalise)
    scan_lexicalise();
  rdp_set_initialise();
  rdp_load_keywords();
  if (rdp_verbose)
     text_printf("\nrdparser\n" RDP_STAMP "\n\n");
  for (rdp_pass = 1; rdp_pass <= RDP_PASSES; rdp_pass++)
  {
    text_echo(rdp_line_echo_all || (rdp_line_echo && rdp_pass == RDP_PASSES));

    for (rdp_sourcefilenumber = 0; (rdp_sourcefilename = rdp_sourcefilenames[rdp_sourcefilenumber]) != NULL; rdp_sourcefilenumber++)
    {
      if (text_open(rdp_sourcefilename) == NULL)
        arg_help("unable to open source file");

      text_get_char();
      scan_();

      reg();            /* call parser at top level */
      if (text_total_errors() != 0)
        text_message(TEXT_FATAL, "error%s detected in source file ''\n", text_total_errors() == 1 ? "" : "s", rdp_sourcefilename);   /* crash quietly */ 
    }
  }

  rdp_sourcefilename = rdp_sourcefilenames[0];     /* Reset filename to first file in the list */

  if (rdp_symbol_statistics)
  {
    symbol_print_all_table_statistics(11);
    symbol_print_all_table();

  }
  text_print_total_errors();
  if (rdp_verbose)
  {
    rdp_finish_time = clock();
    text_message(TEXT_INFO, "%.3f CPU seconds used\n", ((double) (rdp_finish_time-rdp_start_time)) / CLOCKS_PER_SEC);
  }
  return rdp_error_return;
}

/* End of regex.c */
